fontname = 'helvetica';
fontsize = 20;
ABCfontsize = 30;
fontweight = 'bold';
linewidth = 3;

matlabGrey = [1 1 1]*215/255;

colormap gray
CC = colormap;
CM = (CC).*repmat((1-[0.906 0.463 0.247]/0.906), size(CC,1),1);
colormap(1-CM)

set(0, 'defaultfigurecolor', 'w', ...
    'defaultfigurecolormap', 1-CM, ...
    'defaultaxesfontsize', fontsize, ...
    'defaultaxesfontweight', fontweight, ...
    'defaultaxesfontname', fontname, ...
    'defaultaxestickdir', 'out', ...
    'defaultaxesbox', 'on', ...
    'defaultaxesydir', 'normal', ...
    'defaultlinelinewidth', linewidth, ...
    'defaultlinemarkersize', 20, ...
    'defaultfigureposition', [811   486   618   500])

